name: Docker Image CI

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
     - name: Docker Metadata
       id: meta
       uses: docker/metadata-action@v4
       with:
         images: mgibio/immuno_tools-cwl
         tags: type=ref,event=tag
     - name: Docker Login
       uses: docker/login-action@v2.0.0
       with:
         username: ${{ secrets.DOCKERHUB_USER }}
         password: ${{ secrets.DOCKERHUB_PAT }}
     - name: Build and Push Docker Image
       uses: docker/build-push-action@v3.1.1
       with:
         push: true
         tags: ${{ steps.meta.outputs.tags }}
